# Generated by Django 5.1.1 on 2024-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
